### ISSUE TITLE
Update in Hackage

### ISSUE THREAD

**Issue by beojan** [diagrams/diagrams.github.io#1]
Hackage still points to projects.haskell.org, which redirects to archive.haskell.org. This and the fact that the last news entry is from 2016 gives the impression that diagrams is abandoned.

**Comment by byorgey** [comment]
Good point, thanks!  We should fix that. I see that the "homepage" entries all need to be updated. Was there anywhere else you saw such a link, or were you just referring to the "homepage" entries?

**Comment by beojan** [comment]
The HaskellWiki entry(/ies) for Diagrams also points to the old home page.

EDIT: And the Hackage description has a link.

**Comment by byorgey** [comment]
OK, I fixed some of the links on the HaskellWiki that I found.  Will work on fixing the Hackage links.

Although this also reminds me that I asked the projects.haskell.org admins to turn it into a redirect to diagrams.github.io and apparently that never happened...
