### ISSUE TITLE
SymmetryCube doesn't typecheck (lin2 in IO)

### ISSUE THREAD

**Issue by blackgnezdo** [diagrams/diagrams.github.io#3]
`lin2` is in IO since https://github.com/diagrams/SVGFonts/commit/61424cca2bb752d756f9bec641e28ecd106a297c which breaks the example. A quick and dirty fix is to use `unsafePerformIO`. This restores the example to a working state while making it a bad example to follow:
```
> textOpts n = TextOpts loadedFont INSIDE_H KERN False 1 n
> loadedFont = unsafePerformIO (loadDataFont "fonts/LinLibertineCut.svg")
```

**Comment by byorgey** [comment]
Hi @blackgnezdo , thanks for the report!  However, it looks to me like this has already been fixed.  When I look at https://diagrams.github.io/gallery/SymmetryCube.html I see
```
example = do
  font <- lin2
  let c = sCube font
```
and so on.  Is there perhaps an outdated version of the example somewhere you're looking at that we need to update or delete?

**Comment by blackgnezdo** [comment]
I'm no longer sure how I landed on https://archives.haskell.org/projects.haskell.org/diagrams/gallery/SymmetryCube.html which links to https://archives.haskell.org/projects.haskell.org/diagrams/gallery/SymmetryCube.lhs that confused me.

**Comment by byorgey** [comment]
Ah, yeah, the old version of the site on `archives.haskell.org` continues to haunt us.  I think we've fixed most direct links at this point, but we can't delete it, and it could still be returned as a result of various searches.

**Comment by byorgey** [comment]
I will close this then.  Sorry for the confusion!
